---

- name: Install dependencies
  apt:
    update_cache: yes
    pkg:
      - python3-systemd
  become: yes
  become_method: sudo

- name: Copy requirements file
  copy:
    dest: /home/pi/
    src: iot_ac/requirements.txt

- name: Install python dependencies
  pip:
    requirements: /home/pi/requirements.txt
    executable: /usr/local/bin/pip3

- name: Create service folders
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/iot_ac
    - /etc/systemd/system
    - /usr/local/lib/iot_ac_service
  become: yes
  become_method: sudo

- name: Copy systemd service file
  copy:
    src: iot_ac/iot_ac.service
    dest: /etc/systemd/system/iot_ac.service
    owner: root
    group: root
    mode: "0644"
  become: yes
  become_method: sudo
  register: service_file

- name: Copy source
  copy:
    src: iot_ac/iot_ac.py
    dest: /usr/local/lib/iot_ac_service/iot_ac.py
    owner: root
    group: root
    mode: "0644"
  become: yes
  become_method: sudo
  register: service_src

- name: Create config
  copy:
    content: "{{ config | to_json }}"
    dest: /etc/iot_ac/config.json
    owner: pi
    group: pi
    mode: '0400'
  no_log: true
  become: yes
  become_method: sudo
  register: service_conf

- name: Restart service if needed
  systemd:
    name: iot_ac
    daemon_reload: yes
    enabled: yes
    state: restarted
  become: yes
  become_method: sudo
  when: service_file.changed or service_src.changed or service_conf.changed

- name: Ensure service is running
  systemd:
    name: iot_ac
    daemon_reload: yes
    enabled: yes
    state: started
  become: yes
  become_method: sudo
