---

- name: Set hostname
  hostname:
    name: iot-ac
  become: yes
  become_method: sudo

- name: Remove initial setup wizard
  file:
    path: /etc/xdg/autostart/piwiz.desktop
    state: absent
  become: yes
  become_method: sudo

- name: Set timezone
  timezone:
    name: Europe/Budapest
  become: yes
  become_method: sudo

- name: Ensure the locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present
  become: yes
  become_method: sudo

- name: Check default locale
  shell: localectl status | grep 'LANG=en_US.UTF-8'
  changed_when: False
  ignore_errors: True
  register: locale_status

- name: Set as default locale
  command: localectl set-locale LANG=en_US.UTF-8
  when: not ansible_check_mode and locale_status.rc != 0
  become: yes
  become_method: sudo

- name: Set raspi-config value
  lineinfile:
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    path: /boot/config.txt
  become: yes
  become_method: sudo
  with_items:
    - { regexp: '^.*dtparam=i2c_arm.*$', line: 'dtparam=i2c_arm=on' }
    - { regexp: '^.*dtoverlay=gpio-ir,gpio_pin.*$', line: 'dtoverlay=gpio-ir,gpio_pin=18' }
    - { regexp: '^.*dtoverlay=gpio-ir-tx,gpio_pin.*$', line: 'dtoverlay=gpio-ir-tx,gpio_pin=17' }
    - { regexp: '^.*dtparam=pwr_led_trigger.*$', line: 'dtparam=pwr_led_trigger=none' }
    - { regexp: '^.*dtparam=pwr_led_activelow.*$', line: 'dtparam=pwr_led_activelow=off' }
  register: config_txt

- name: Set user password
  user:
    name: pi
    password: "{{ lookup('file', 'secrets/password') }}"
  become: yes
  become_method: sudo

- name: Check pip3
  stat:
    path: /usr/local/bin/pip3
  register: pip3_exists

- name: Install python3-distutils so pip can install
  apt:
    update_cache: yes
    pkg:
      - python3-distutils
  become: yes
  become_method: sudo

- name: Fetch get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
  when: pip3_exists.stat.exists == false

- name: Install pip3
  command: python3 /tmp/get-pip.py
  args:
    creates: /usr/local/bin/pip3
  become: yes
  become_method: sudo

- name: Install python-apt
  pip:
    name: python-apt
    executable: /usr/local/bin/pip3

- name: Reboot the Raspberry for changes to apply
  reboot:
  become: yes
  become_method: sudo
  when: config_txt.changed
