---

- name: Create iot_ac user.
  user:
    name: "{{ iot_ac_user }}"
    groups: "{{ iot_ac_user_groups }}"
    system: yes
    create_home: no
    shell: /usr/sbin/nologin

- name: Install dependencies
  apt:
    pkg:
      - python3-systemd

- name: Create service folders
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/iot_ac
    - /etc/systemd/system
    - /usr/local/lib/iot_ac_service

- name: Copy systemd service file
  template:
    src: iot_ac.service.j2
    dest: /etc/systemd/system/iot_ac.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart iot_ac

- name: Copy requirements file
  copy:
    dest: /usr/local/lib/iot_ac_service/requirements.txt
    src: iot_ac/requirements.txt
  register: requirements_file

- name: Install python dependencies
  pip:
    requirements: /usr/local/lib/iot_ac_service/requirements.txt
    executable: /usr/local/bin/pip3
  when: requirements_file.changed

- name: Copy source
  copy:
    src: iot_ac/iot_ac.py
    dest: /usr/local/lib/iot_ac_service/iot_ac.py
    owner: root
    group: root
    mode: "0644"
  notify: Restart iot_ac

- name: Create config
  copy:
    content: "{{ config | to_json }}"
    dest: /etc/iot_ac/config.json
    owner: "{{ iot_ac_user }}"
    group: "{{ iot_ac_user }}"
    mode: '0400'
  no_log: true
  notify: Restart iot_ac

- name: Ensure service is running
  systemd:
    name: iot_ac
    daemon_reload: yes
    enabled: yes
    state: started
