---

- name: Create lirc user
  user:
    name: lirc
    groups: video
    system: yes
    create_home: no
    shell: /usr/sbin/nologin

- name: Copy patched and compiled lirc deb files
  copy:
    dest: /opt/
    src: "lirc/{{ item }}"
  with_items:
    - liblirc0_0.10.1-5.2_armhf.deb
    - liblircclient0_0.10.1-5.2_armhf.deb
    - lirc_0.10.1-5.2_armhf.deb

- name: Copy configuration files
  copy:
    dest: /etc/lirc/
    owner: root
    group: root
    src: "lirc/{{ item }}"
  with_items:
    - lirc_options.conf
    - lircd.conf

- name: Install lirc
  apt:
    deb: "/opt/{{ item }}"
  with_items:
    - liblirc0_0.10.1-5.2_armhf.deb
    - liblircclient0_0.10.1-5.2_armhf.deb
    - lirc_0.10.1-5.2_armhf.deb

- name: Copy modified init script
  copy:
    dest: /etc/init.d/lircd
    src: lirc/lircd.init
    owner: root
    group: root
    mode: "0755"
  register: init_script

- name: Update rc.d with updated init script
  command: update-rc.d lircd defaults
  when: init_script.changed

- name: Patch systemd service for unprivileged user
  ini_file:
    path: /lib/systemd/system/lircd.service
    section: Service
    option: "{{ item }}"
    value: lirc
  with_items:
    - User
    - Group

- name: Ensure Lircd is running
  service:
    name: lircd
    enabled: yes
    daemon_reload: yes
    state: started
