---

- name: Create lirc user
  user:
    name: lirc
    groups: video
    system: true
    create_home: false
    shell: /usr/sbin/nologin

- name: Copy patched and compiled lirc deb files
  copy:
    dest: /opt/
    src: "lirc/{{ item }}"
    mode: 0644
  with_items:
    - liblirc0_0.10.1-5.2_armhf.deb
    - liblircclient0_0.10.1-5.2_armhf.deb
    - lirc_0.10.1-5.2_armhf.deb

- name: Copy configuration files
  copy:
    dest: /etc/lirc/
    owner: root
    group: root
    src: "lirc/{{ item }}"
    mode: 0644
  with_items:
    - lirc_options.conf
    - lircd.conf

- name: Install lirc
  apt:
    deb: "/opt/{{ item }}"
  with_items:
    - liblirc0_0.10.1-5.2_armhf.deb
    - liblircclient0_0.10.1-5.2_armhf.deb
    - lirc_0.10.1-5.2_armhf.deb

- name: Modify tmpfiles conf for unprivileged user
  copy:
    dest: /usr/lib/tmpfiles.d/lirc.conf
    content: "d /run/lirc  0775  root  lirc  10d"
    owner: root
    group: root
    mode: 0644

- name: Patch systemd service for unprivileged user
  ini_file:
    path: /lib/systemd/system/lircd.service
    section: Service
    option: "{{ item }}"
    value: lirc
    mode: 0644
  with_items:
    - User
    - Group

- name: Ensure Lircd is running
  service:
    name: lircd
    enabled: true
    daemon_reload: true
    state: started
