---

- name: Copy patched and compiled lirc deb files
  copy:
    dest: /home/pi/
    src: "lirc/{{ item }}"
  with_items:
    - liblirc0_0.10.1-5.2_armhf.deb
    - liblircclient0_0.10.1-5.2_armhf.deb
    - lirc_0.10.1-5.2_armhf.deb

- name: Copy configuration files
  copy:
    dest: /etc/lirc/
    owner: root
    group: root
    src: "lirc/{{ item }}"
  with_items:
    - lirc_options.conf
    - lircd.conf

- name: Install lirc
  apt:
    deb: "/home/pi/{{ item }}"
  with_items:
    - liblirc0_0.10.1-5.2_armhf.deb
    - liblircclient0_0.10.1-5.2_armhf.deb
    - lirc_0.10.1-5.2_armhf.deb

- name: Ensure Lircd is running
  service:
    name: lircd
    enabled: yes
    state: started
