---

- name: Add azlux apt key
  apt_key:
    url: https://azlux.fr/repo.gpg.key
    state: present
  become: yes
  become_method: sudo

- name: Add azlux apt source
  apt_repository:
    repo: deb http://packages.azlux.fr/debian/ buster main
    filename: azlux
    state: present
  become: yes
  become_method: sudo

- name: Install log2ram
  apt:
    name: log2ram
    update_cache: yes
    state: present
  register: log2ram_apt
  become: yes
  become_method: sudo

- name: Write logs only weekly
  ini_file:
    path: /etc/systemd/system/log2ram-daily.timer.d/override.conf
    section: Timer
    option: OnCalendar
    value: weekly
  become: yes
  become_method: sudo

- name: Reboot the Raspberry for changes to apply
  reboot:
  become: yes
  become_method: sudo
  when: log2ram_apt.changed
